package com.uclee.fundation.data.mybatis.model;

import java.util.Date;

public class PaymentCallBackData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_payment_callback_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_payment_callback_data.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_payment_callback_data.payment_serial_num
     *
     * @mbggenerated
     */
    private String paymentSerialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_payment_callback_data.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_payment_callback_data.id
     *
     * @return the value of web_payment_callback_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_payment_callback_data.id
     *
     * @param id the value for web_payment_callback_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_payment_callback_data.data
     *
     * @return the value of web_payment_callback_data.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_payment_callback_data.data
     *
     * @param data the value for web_payment_callback_data.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_payment_callback_data.payment_serial_num
     *
     * @return the value of web_payment_callback_data.payment_serial_num
     *
     * @mbggenerated
     */
    public String getPaymentSerialNum() {
        return paymentSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_payment_callback_data.payment_serial_num
     *
     * @param paymentSerialNum the value for web_payment_callback_data.payment_serial_num
     *
     * @mbggenerated
     */
    public void setPaymentSerialNum(String paymentSerialNum) {
        this.paymentSerialNum = paymentSerialNum == null ? null : paymentSerialNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_payment_callback_data.create_time
     *
     * @return the value of web_payment_callback_data.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_payment_callback_data.create_time
     *
     * @param createTime the value for web_payment_callback_data.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}