package com.uclee.fundation.data.mybatis.mapping;


import com.uclee.fundation.data.mybatis.model.PaymentCallBackData;

public interface PaymentCallBackDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    int insert(PaymentCallBackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    int insertSelective(PaymentCallBackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    PaymentCallBackData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentCallBackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_payment_callback_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentCallBackData record);

    PaymentCallBackData selectByPaymentSerialNum(String paymentSerialNum);
}